### ISSUE TITLE
转换onnx失败

### ISSUE THREAD

**Issue by 791136190** [sophgo/ChatGLM3-TPU#1]
在convert_glm_block的时候，export直接退出了
基本环境如下

Package                       Version
----------------------------- ----------
certifi                       2023.11.17
charset-normalizer            3.3.2
cmake                         3.28.1
coloredlogs                   15.0.1
filelock                      3.13.1
flatbuffers                   23.5.26
fsspec                        2023.12.2
huggingface-hub               0.20.1
humanfriendly                 10.0
idna                          3.6
Jinja2                        3.1.2
lit                           17.0.6
MarkupSafe                    2.1.3
mpmath                        1.3.0
networkx                      3.2.1
numpy                         1.25.2
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-cupti-cu11        11.7.101
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.2.10.91
nvidia-cusolver-cu11          11.4.0.1
nvidia-cusparse-cu11          11.7.4.91
nvidia-nccl-cu11              2.14.3
nvidia-nvtx-cu11              11.7.91
onnx                          1.15.0
onnxruntime                   1.15.1
packaging                     23.2
pip                           23.3.2
protobuf                      4.25.1
PyYAML                        6.0.1
regex                         2023.12.25
requests                      2.31.0
safetensors                   0.4.1
sentencepiece                 0.1.99
setuptools                    57.4.0
sympy                         1.12
tabulate                      0.9.0
tokenizers                    0.13.3
torch                         2.0.1
tqdm                          4.66.1
transformers                  4.31.0
transformers-stream-generator 0.0.4
triton                        2.0.0
typing_extensions             4.9.0
urllib3                       2.1.0
wheel                         0.42.0

**Comment by WaitDumplings** [comment]
ChatGLM3-6B官方库25G左右，转模型需要保证运行内存至少32G以上，导出onnx模型需要存储空间50G以上，fp16模型转换需要存储空间180G以上，int8和int4模型需要的空间会更少。请确保内存和储存空间足够
